// DispIDs.h: Defines a DISPID for each COM property and method we're providing.

// IHotKeyBox
// properties
#define DISPID_HKBOX_APPEARANCE																	1
#define DISPID_HKBOX_BACKCOLOR																	2
#define DISPID_HKBOX_BORDERSTYLE																3
#define DISPID_HKBOX_DEFAULTMODIFIERKEYS												4
#define DISPID_HKBOX_DISABLEDEVENTS															5
#define DISPID_HKBOX_DONTREDRAW																	6
#define DISPID_HKBOX_ENABLED																		DISPID_ENABLED
#define DISPID_HKBOX_FONT																				7
#define DISPID_HKBOX_HOVERTIME																	8
#define DISPID_HKBOX_HWND																				9
#define DISPID_HKBOX_INVALIDKEYCOMBINATIONS											10
#define DISPID_HKBOX_MOUSEICON																	11
#define DISPID_HKBOX_MOUSEPOINTER																12
#define DISPID_HKBOX_PROCESSCONTEXTMENUKEYS											13
#define DISPID_HKBOX_REGISTERFOROLEDRAGDROP											14
#define DISPID_HKBOX_RIGHTTOLEFT																15
#define DISPID_HKBOX_SUPPORTOLEDRAGIMAGES												16
#define DISPID_HKBOX_TEXT																				DISPID_VALUE
#define DISPID_HKBOX_USESYSTEMFONT															17
#define DISPID_HKBOX_VERSION																		18
#define DISPID_HKBOX_DISABLEDBACKCOLOR													23
#define DISPID_HKBOX_DETECTDOUBLECLICKS													24
// fingerprint
#define DISPID_HKBOX_APPID																			500
#define DISPID_HKBOX_APPNAME																		501
#define DISPID_HKBOX_APPSHORTNAME																502
#define DISPID_HKBOX_BUILD																			503
#define DISPID_HKBOX_CHARSET																		504
#define DISPID_HKBOX_ISRELEASE																	505
#define DISPID_HKBOX_PROGRAMMER																	506
#define DISPID_HKBOX_TESTER																			507
// methods
#define DISPID_HKBOX_ABOUT																			DISPID_ABOUTBOX
#define DISPID_HKBOX_GETCURRENTKEYCOMBINATION										19
#define DISPID_HKBOX_LOADSETTINGSFROMFILE												20
#define DISPID_HKBOX_REFRESH																		DISPID_REFRESH
#define DISPID_HKBOX_SAVESETTINGSTOFILE													21
#define DISPID_HKBOX_SETCURRENTKEYCOMBINATION										22
#define DISPID_HKBOX_FINISHOLEDRAGDROP													25


// _IHotKeyBoxEvents
// methods
#define DISPID_HKBOXE_CLICK																			1
#define DISPID_HKBOXE_CONTEXTMENU																2
#define DISPID_HKBOXE_DBLCLICK																	3
#define DISPID_HKBOXE_DESTROYEDCONTROLWINDOW										4
#define DISPID_HKBOXE_KEYDOWN																		DISPID_VALUE
#define DISPID_HKBOXE_KEYPRESS																	5
#define DISPID_HKBOXE_KEYUP																			6
#define DISPID_HKBOXE_MCLICK																		7
#define DISPID_HKBOXE_MDBLCLICK																	8
#define DISPID_HKBOXE_MOUSEDOWN																	9
#define DISPID_HKBOXE_MOUSEENTER																10
#define DISPID_HKBOXE_MOUSEHOVER																11
#define DISPID_HKBOXE_MOUSELEAVE																12
#define DISPID_HKBOXE_MOUSEMOVE																	13
#define DISPID_HKBOXE_MOUSEUP																		14
#define DISPID_HKBOXE_OLEDRAGDROP																15
#define DISPID_HKBOXE_OLEDRAGENTER															16
#define DISPID_HKBOXE_OLEDRAGLEAVE															17
#define DISPID_HKBOXE_OLEDRAGMOUSEMOVE													18
#define DISPID_HKBOXE_RCLICK																		19
#define DISPID_HKBOXE_RDBLCLICK																	20
#define DISPID_HKBOXE_RECREATEDCONTROLWINDOW										21
#define DISPID_HKBOXE_RESIZEDCONTROLWINDOW											22
#define DISPID_HKBOXE_MOUSEWHEEL																23
#define DISPID_HKBOXE_XCLICK																		24
#define DISPID_HKBOXE_XDBLCLICK																	25


// IIPAddressBox
// properties
#define DISPID_IPADDRBOX_ADDRESS																DISPID_VALUE
#define DISPID_IPADDRBOX_APPEARANCE															1
#define DISPID_IPADDRBOX_BACKCOLOR															2
#define DISPID_IPADDRBOX_BORDERSTYLE														3
#define DISPID_IPADDRBOX_DISABLEDEVENTS													4
#define DISPID_IPADDRBOX_DONTREDRAW															5
#define DISPID_IPADDRBOX_ENABLED																DISPID_ENABLED
#define DISPID_IPADDRBOX_FONT																		6
#define DISPID_IPADDRBOX_FORECOLOR															7
#define DISPID_IPADDRBOX_HOVERTIME															8
#define DISPID_IPADDRBOX_HWND																		9
#define DISPID_IPADDRBOX_HWNDEDIT																10
#define DISPID_IPADDRBOX_IMEMODE																11
#define DISPID_IPADDRBOX_MAXIMUM																12
#define DISPID_IPADDRBOX_MINIMUM																13
#define DISPID_IPADDRBOX_MOUSEICON															14
#define DISPID_IPADDRBOX_MOUSEPOINTER														15
#define DISPID_IPADDRBOX_PROCESSCONTEXTMENUKEYS									16
#define DISPID_IPADDRBOX_REGISTERFOROLEDRAGDROP									17
#define DISPID_IPADDRBOX_SUPPORTOLEDRAGIMAGES										18
#define DISPID_IPADDRBOX_USESYSTEMFONT													19
#define DISPID_IPADDRBOX_VERSION																20
#define DISPID_IPADDRBOX_DISABLEDBACKCOLOR											24
// fingerprint
#define DISPID_IPADDRBOX_APPID																	500
#define DISPID_IPADDRBOX_APPNAME																501
#define DISPID_IPADDRBOX_APPSHORTNAME														502
#define DISPID_IPADDRBOX_BUILD																	503
#define DISPID_IPADDRBOX_CHARSET																504
#define DISPID_IPADDRBOX_ISRELEASE															505
#define DISPID_IPADDRBOX_PROGRAMMER															506
#define DISPID_IPADDRBOX_TESTER																	507
// methods
#define DISPID_IPADDRBOX_ABOUT																	DISPID_ABOUTBOX
#define DISPID_IPADDRBOX_LOADSETTINGSFROMFILE										21
#define DISPID_IPADDRBOX_REFRESH																DISPID_REFRESH
#define DISPID_IPADDRBOX_SAVESETTINGSTOFILE											22
#define DISPID_IPADDRBOX_SETFOCUSTOFIELD												23
#define DISPID_IPADDRBOX_FINISHOLEDRAGDROP											25


// _IIPAddressBoxEvents
// methods
#define DISPID_IPADDRBOXE_ADDRESSCHANGED												DISPID_VALUE
#define DISPID_IPADDRBOXE_CLICK																	1
#define DISPID_IPADDRBOXE_CONTEXTMENU														2
#define DISPID_IPADDRBOXE_DBLCLICK															3
#define DISPID_IPADDRBOXE_DESTROYEDCONTROLWINDOW								4
#define DISPID_IPADDRBOXE_FIELDTEXTCHANGED											5
#define DISPID_IPADDRBOXE_KEYDOWN																6
#define DISPID_IPADDRBOXE_KEYPRESS															7
#define DISPID_IPADDRBOXE_KEYUP																	8
#define DISPID_IPADDRBOXE_MCLICK																9
#define DISPID_IPADDRBOXE_MDBLCLICK															10
#define DISPID_IPADDRBOXE_MOUSEDOWN															11
#define DISPID_IPADDRBOXE_MOUSEENTER														12
#define DISPID_IPADDRBOXE_MOUSEHOVER														13
#define DISPID_IPADDRBOXE_MOUSELEAVE														14
#define DISPID_IPADDRBOXE_MOUSEMOVE															15
#define DISPID_IPADDRBOXE_MOUSEUP																16
#define DISPID_IPADDRBOXE_OLEDRAGDROP														17
#define DISPID_IPADDRBOXE_OLEDRAGENTER													18
#define DISPID_IPADDRBOXE_OLEDRAGLEAVE													19
#define DISPID_IPADDRBOXE_OLEDRAGMOUSEMOVE											20
#define DISPID_IPADDRBOXE_RCLICK																21
#define DISPID_IPADDRBOXE_RDBLCLICK															22
#define DISPID_IPADDRBOXE_RECREATEDCONTROLWINDOW								23
#define DISPID_IPADDRBOXE_RESIZEDCONTROLWINDOW									24
#define DISPID_IPADDRBOXE_MOUSEWHEEL														25
#define DISPID_IPADDRBOXE_XCLICK																26
#define DISPID_IPADDRBOXE_XDBLCLICK															27


// ITextBox
// properties
#define DISPID_TXTBOX_ACCEPTNUMBERSONLY													1
#define DISPID_TXTBOX_ACCEPTTABKEY															2
#define DISPID_TXTBOX_ALLOWDRAGDROP															3
#define DISPID_TXTBOX_ALWAYSSHOWSELECTION												4
#define DISPID_TXTBOX_APPEARANCE																5
#define DISPID_TXTBOX_AUTOSCROLLING															6
#define DISPID_TXTBOX_BACKCOLOR																	7
#define DISPID_TXTBOX_BORDERSTYLE																8
#define DISPID_TXTBOX_CANCELIMECOMPOSITIONONSETFOCUS						9
#define DISPID_TXTBOX_CHARACTERCONVERSION												10
#define DISPID_TXTBOX_COMPLETEIMECOMPOSITIONONKILLFOCUS					11
#define DISPID_TXTBOX_CUEBANNER																	12
#define DISPID_TXTBOX_DISABLEDEVENTS														13
#define DISPID_TXTBOX_DISPLAYCUEBANNERONFOCUS										14
#define DISPID_TXTBOX_DONTREDRAW																15
#define DISPID_TXTBOX_DOOEMCONVERSION														16
#define DISPID_TXTBOX_DRAGSCROLLTIMEBASE												17
#define DISPID_TXTBOX_ENABLED																		DISPID_ENABLED
#define DISPID_TXTBOX_FIRSTVISIBLECHAR													18
#define DISPID_TXTBOX_FIRSTVISIBLELINE													19
#define DISPID_TXTBOX_FONT																			20
#define DISPID_TXTBOX_FORECOLOR																	21
#define DISPID_TXTBOX_FORMATTINGRECTANGLEHEIGHT									22
#define DISPID_TXTBOX_FORMATTINGRECTANGLELEFT										23
#define DISPID_TXTBOX_FORMATTINGRECTANGLETOP										24
#define DISPID_TXTBOX_FORMATTINGRECTANGLEWIDTH									25
#define DISPID_TXTBOX_HALIGNMENT																26
#define DISPID_TXTBOX_HDRAGIMAGELIST														27
#define DISPID_TXTBOX_HOVERTIME																	28
#define DISPID_TXTBOX_HWND																			29
#define DISPID_TXTBOX_IMEMODE																		30
#define DISPID_TXTBOX_INSERTMARKCOLOR														31
#define DISPID_TXTBOX_INSERTSOFTLINEBREAKS											32
#define DISPID_TXTBOX_LEFTMARGIN																33
#define DISPID_TXTBOX_MAXTEXTLENGTH															34
#define DISPID_TXTBOX_MODIFIED																	35
#define DISPID_TXTBOX_MOUSEICON																	36
#define DISPID_TXTBOX_MOUSEPOINTER															37
#define DISPID_TXTBOX_MULTILINE																	38
#define DISPID_TXTBOX_PASSWORDCHAR															39
#define DISPID_TXTBOX_PROCESSCONTEXTMENUKEYS										40
#define DISPID_TXTBOX_READONLY																	41
#define DISPID_TXTBOX_REGISTERFOROLEDRAGDROP										42
#define DISPID_TXTBOX_RIGHTMARGIN																43
#define DISPID_TXTBOX_RIGHTTOLEFT																44
#define DISPID_TXTBOX_SCROLLBARS																45
#define DISPID_TXTBOX_SELECTEDTEXT															46
#define DISPID_TXTBOX_SELECTEDTEXTMOUSEICON											47
#define DISPID_TXTBOX_SELECTEDTEXTMOUSEPOINTER									48
#define DISPID_TXTBOX_SHOWDRAGIMAGE															49
#define DISPID_TXTBOX_SUPPORTOLEDRAGIMAGES											50
#define DISPID_TXTBOX_TABSTOPS																	51
#define DISPID_TXTBOX_TABWIDTH																	52
#define DISPID_TXTBOX_TEXT																			DISPID_VALUE
#define DISPID_TXTBOX_USECUSTOMFORMATTINGRECTANGLE							53
#define DISPID_TXTBOX_USEPASSWORDCHAR														54
#define DISPID_TXTBOX_USESYSTEMFONT															55
#define DISPID_TXTBOX_VERSION																		56
#define DISPID_TXTBOX_WORDBREAKFUNCTION													57
#define DISPID_TXTBOX_LASTVISIBLELINE														86
#define DISPID_TXTBOX_LINEHEIGHT																87
#define DISPID_TXTBOX_TEXTLENGTH																88
#define DISPID_TXTBOX_DISABLEDBACKCOLOR													89
#define DISPID_TXTBOX_DISABLEDFORECOLOR													90
#define DISPID_TXTBOX_OLEDRAGIMAGESTYLE													91
// fingerprint
#define DISPID_TXTBOX_APPID																			500
#define DISPID_TXTBOX_APPNAME																		501
#define DISPID_TXTBOX_APPSHORTNAME															502
#define DISPID_TXTBOX_BUILD																			503
#define DISPID_TXTBOX_CHARSET																		504
#define DISPID_TXTBOX_ISRELEASE																	505
#define DISPID_TXTBOX_PROGRAMMER																506
#define DISPID_TXTBOX_TESTER																		507
// methods
#define DISPID_TXTBOX_ABOUT																			DISPID_ABOUTBOX
#define DISPID_TXTBOX_APPENDTEXT																58
#define DISPID_TXTBOX_BEGINDRAG																	59
#define DISPID_TXTBOX_CANUNDO																		60
#define DISPID_TXTBOX_CHARINDEXTOPOSITION												61
#define DISPID_TXTBOX_EMPTYUNDOBUFFER														62
#define DISPID_TXTBOX_ENDDRAG																		63
#define DISPID_TXTBOX_GETDRAGGEDTEXTRANGE												64
#define DISPID_TXTBOX_GETFIRSTCHAROFLINE												65
#define DISPID_TXTBOX_GETCLOSESTINSERTMARKPOSITION							66
#define DISPID_TXTBOX_GETINSERTMARKPOSITION											67
#define DISPID_TXTBOX_GETLINE																		68
#define DISPID_TXTBOX_GETLINECOUNT															69
#define DISPID_TXTBOX_GETLINEFROMCHAR														70
#define DISPID_TXTBOX_GETLINELENGTH															71
#define DISPID_TXTBOX_GETSELECTION															72
#define DISPID_TXTBOX_HIDEBALLOONTIP														73
#define DISPID_TXTBOX_ISTEXTTRUNCATED														74
#define DISPID_TXTBOX_LOADSETTINGSFROMFILE											75
#define DISPID_TXTBOX_OLEDRAG																		76
#define DISPID_TXTBOX_POSITIONTOCHARINDEX												77
#define DISPID_TXTBOX_REFRESH																		DISPID_REFRESH
#define DISPID_TXTBOX_REPLACESELECTEDTEXT												78
#define DISPID_TXTBOX_SAVESETTINGSTOFILE												79
#define DISPID_TXTBOX_SCROLL																		80
#define DISPID_TXTBOX_SCROLLCARETINTOVIEW												81
#define DISPID_TXTBOX_SETINSERTMARKPOSITION											82
#define DISPID_TXTBOX_SETSELECTION															83
#define DISPID_TXTBOX_SHOWBALLOONTIP														84
#define DISPID_TXTBOX_UNDO																			85
#define DISPID_TXTBOX_FINISHOLEDRAGDROP													92


// _ITextBoxEvents
// methods
#define DISPID_TXTBOXE_ABORTEDDRAG															1
#define DISPID_TXTBOXE_BEFOREDRAWTEXT														2
#define DISPID_TXTBOXE_BEGINDRAG																3
#define DISPID_TXTBOXE_BEGINRDRAG																4
#define DISPID_TXTBOXE_CLICK																		5
#define DISPID_TXTBOXE_CONTEXTMENU															6
#define DISPID_TXTBOXE_DBLCLICK																	7
#define DISPID_TXTBOXE_DESTROYEDCONTROLWINDOW										8
#define DISPID_TXTBOXE_DRAGMOUSEMOVE														9
#define DISPID_TXTBOXE_DROP																			10
#define DISPID_TXTBOXE_KEYDOWN																	11
#define DISPID_TXTBOXE_KEYPRESS																	12
#define DISPID_TXTBOXE_KEYUP																		13
#define DISPID_TXTBOXE_MCLICK																		14
#define DISPID_TXTBOXE_MDBLCLICK																15
#define DISPID_TXTBOXE_MOUSEDOWN																16
#define DISPID_TXTBOXE_MOUSEENTER																17
#define DISPID_TXTBOXE_MOUSEHOVER																18
#define DISPID_TXTBOXE_MOUSELEAVE																19
#define DISPID_TXTBOXE_MOUSEMOVE																20
#define DISPID_TXTBOXE_MOUSEUP																	21
#define DISPID_TXTBOXE_OLECOMPLETEDRAG													22
#define DISPID_TXTBOXE_OLEDRAGDROP															23
#define DISPID_TXTBOXE_OLEDRAGENTER															24
#define DISPID_TXTBOXE_OLEDRAGLEAVE															25
#define DISPID_TXTBOXE_OLEDRAGMOUSEMOVE													26
#define DISPID_TXTBOXE_OLEGIVEFEEDBACK													27
#define DISPID_TXTBOXE_OLEQUERYCONTINUEDRAG											28
#define DISPID_TXTBOXE_OLESETDATA																29
#define DISPID_TXTBOXE_OLESTARTDRAG															30
#define DISPID_TXTBOXE_OUTOFMEMORY															31
#define DISPID_TXTBOXE_RCLICK																		32
#define DISPID_TXTBOXE_RDBLCLICK																33
#define DISPID_TXTBOXE_RECREATEDCONTROLWINDOW										34
#define DISPID_TXTBOXE_RESIZEDCONTROLWINDOW											35
#define DISPID_TXTBOXE_SCROLLING																36
#define DISPID_TXTBOXE_TEXTCHANGED															DISPID_VALUE
#define DISPID_TXTBOXE_TRUNCATEDTEXT														37
#define DISPID_TXTBOXE_WRITINGDIRECTIONCHANGED									38
#define DISPID_TXTBOXE_OLEDRAGENTERPOTENTIALTARGET							39
#define DISPID_TXTBOXE_OLEDRAGLEAVEPOTENTIALTARGET							40
#define DISPID_TXTBOXE_OLERECEIVEDNEWDATA												41
#define DISPID_TXTBOXE_MOUSEWHEEL																42
#define DISPID_TXTBOXE_XCLICK																		43
#define DISPID_TXTBOXE_XDBLCLICK																44


// IUpDownTextBox
// properties
#define DISPID_UPDWNTXTBOX_ACCELERATORS													1
#define DISPID_UPDWNTXTBOX_ACCEPTNUMBERSONLY										2
#define DISPID_UPDWNTXTBOX_ALWAYSSHOWSELECTION									3
#define DISPID_UPDWNTXTBOX_APPEARANCE														4
#define DISPID_UPDWNTXTBOX_AUTOMATICALLYCORRECTVALUE						5
#define DISPID_UPDWNTXTBOX_AUTOMATICALLYSETTEXT									6
#define DISPID_UPDWNTXTBOX_AUTOSCROLLING												7
#define DISPID_UPDWNTXTBOX_BACKCOLOR														8
#define DISPID_UPDWNTXTBOX_BASE																	9
#define DISPID_UPDWNTXTBOX_BORDERSTYLE													10
#define DISPID_UPDWNTXTBOX_CANCELIMECOMPOSITIONONSETFOCUS				11
#define DISPID_UPDWNTXTBOX_CHARACTERCONVERSION									12
#define DISPID_UPDWNTXTBOX_COMPLETEIMECOMPOSITIONONKILLFOCUS		13
#define DISPID_UPDWNTXTBOX_CUEBANNER														14
#define DISPID_UPDWNTXTBOX_CURRENTVALUE													DISPID_VALUE
#define DISPID_UPDWNTXTBOX_DISABLEDEVENTS												15
#define DISPID_UPDWNTXTBOX_DISPLAYCUEBANNERONFOCUS							16
#define DISPID_UPDWNTXTBOX_DONTREDRAW														17
#define DISPID_UPDWNTXTBOX_DOOEMCONVERSION											18
#define DISPID_UPDWNTXTBOX_ENABLED															DISPID_ENABLED
#define DISPID_UPDWNTXTBOX_FIRSTVISIBLECHAR											19
#define DISPID_UPDWNTXTBOX_FONT																	20
#define DISPID_UPDWNTXTBOX_FORECOLOR														21
#define DISPID_UPDWNTXTBOX_FORMATTINGRECTANGLEHEIGHT						22
#define DISPID_UPDWNTXTBOX_FORMATTINGRECTANGLELEFT							23
#define DISPID_UPDWNTXTBOX_FORMATTINGRECTANGLETOP								24
#define DISPID_UPDWNTXTBOX_FORMATTINGRECTANGLEWIDTH							25
#define DISPID_UPDWNTXTBOX_GROUPDIGITS													26
#define DISPID_UPDWNTXTBOX_HALIGNMENT														27
#define DISPID_UPDWNTXTBOX_HOTTRACKING													28
#define DISPID_UPDWNTXTBOX_HOVERTIME														29
#define DISPID_UPDWNTXTBOX_HWND																	30
#define DISPID_UPDWNTXTBOX_HWNDEDIT															31
#define DISPID_UPDWNTXTBOX_HWNDUPDOWN														32
#define DISPID_UPDWNTXTBOX_IMEMODE															33
#define DISPID_UPDWNTXTBOX_LEFTMARGIN														34
#define DISPID_UPDWNTXTBOX_MAXIMUM															35
#define DISPID_UPDWNTXTBOX_MAXTEXTLENGTH												36
#define DISPID_UPDWNTXTBOX_MINIMUM															37
#define DISPID_UPDWNTXTBOX_MODIFIED															38
#define DISPID_UPDWNTXTBOX_MOUSEICON														39
#define DISPID_UPDWNTXTBOX_MOUSEPOINTER													40
#define DISPID_UPDWNTXTBOX_ORIENTATION													41
#define DISPID_UPDWNTXTBOX_PROCESSARROWKEYS											42
#define DISPID_UPDWNTXTBOX_PROCESSCONTEXTMENUKEYS								43
#define DISPID_UPDWNTXTBOX_READONLYTEXTBOX											44
#define DISPID_UPDWNTXTBOX_REGISTERFOROLEDRAGDROP								45
#define DISPID_UPDWNTXTBOX_RIGHTMARGIN													46
#define DISPID_UPDWNTXTBOX_RIGHTTOLEFT													47
#define DISPID_UPDWNTXTBOX_SELECTEDTEXT													48
#define DISPID_UPDWNTXTBOX_SUPPORTOLEDRAGIMAGES									49
#define DISPID_UPDWNTXTBOX_TEXT																	50
#define DISPID_UPDWNTXTBOX_UPDOWNPOSITION												51
#define DISPID_UPDWNTXTBOX_USESYSTEMFONT												52
#define DISPID_UPDWNTXTBOX_VERSION															53
#define DISPID_UPDWNTXTBOX_WORDBREAKFUNCTION										54
#define DISPID_UPDWNTXTBOX_WRAPATBOUNDARIES											55
#define DISPID_UPDWNTXTBOX_DISABLEDBACKCOLOR										71
#define DISPID_UPDWNTXTBOX_DISABLEDFORECOLOR										72
#define DISPID_UPDWNTXTBOX_DETECTDOUBLECLICKS										73
// fingerprint
#define DISPID_UPDWNTXTBOX_APPID																500
#define DISPID_UPDWNTXTBOX_APPNAME															501
#define DISPID_UPDWNTXTBOX_APPSHORTNAME													502
#define DISPID_UPDWNTXTBOX_BUILD																503
#define DISPID_UPDWNTXTBOX_CHARSET															504
#define DISPID_UPDWNTXTBOX_ISRELEASE														505
#define DISPID_UPDWNTXTBOX_PROGRAMMER														506
#define DISPID_UPDWNTXTBOX_TESTER																507
// methods
#define DISPID_UPDWNTXTBOX_ABOUT																DISPID_ABOUTBOX
#define DISPID_UPDWNTXTBOX_CANUNDO															56
#define DISPID_UPDWNTXTBOX_CHARINDEXTOPOSITION									57
#define DISPID_UPDWNTXTBOX_EMPTYUNDOBUFFER											58
#define DISPID_UPDWNTXTBOX_GETSELECTION													59
#define DISPID_UPDWNTXTBOX_HIDEBALLOONTIP												60
#define DISPID_UPDWNTXTBOX_HITTEST															61
#define DISPID_UPDWNTXTBOX_ISTEXTTRUNCATED											62
#define DISPID_UPDWNTXTBOX_LOADSETTINGSFROMFILE									63
#define DISPID_UPDWNTXTBOX_POSITIONTOCHARINDEX									64
#define DISPID_UPDWNTXTBOX_REFRESH															DISPID_REFRESH
#define DISPID_UPDWNTXTBOX_REPLACESELECTEDTEXT									65
#define DISPID_UPDWNTXTBOX_SAVESETTINGSTOFILE										66
#define DISPID_UPDWNTXTBOX_SCROLLCARETINTOVIEW									67
#define DISPID_UPDWNTXTBOX_SETSELECTION													68
#define DISPID_UPDWNTXTBOX_SHOWBALLOONTIP												69
#define DISPID_UPDWNTXTBOX_UNDO																	70
#define DISPID_UPDWNTXTBOX_FINISHOLEDRAGDROP										74


// _IUpDownTextBoxEvents
// methods
#define DISPID_UPDWNTXTBOXE_BEFOREDRAWTEXT											1
#define DISPID_UPDWNTXTBOXE_CHANGEDACCELERATORS									2
#define DISPID_UPDWNTXTBOXE_CHANGINGACCELERATORS								3
#define DISPID_UPDWNTXTBOXE_CLICK																4
#define DISPID_UPDWNTXTBOXE_CONTEXTMENU													5
#define DISPID_UPDWNTXTBOXE_DBLCLICK														6
#define DISPID_UPDWNTXTBOXE_DESTROYEDCONTROLWINDOW							7
#define DISPID_UPDWNTXTBOXE_KEYDOWN															8
#define DISPID_UPDWNTXTBOXE_KEYPRESS														9
#define DISPID_UPDWNTXTBOXE_KEYUP																10
#define DISPID_UPDWNTXTBOXE_MCLICK															11
#define DISPID_UPDWNTXTBOXE_MDBLCLICK														12
#define DISPID_UPDWNTXTBOXE_MOUSEDOWN														13
#define DISPID_UPDWNTXTBOXE_MOUSEENTER													14
#define DISPID_UPDWNTXTBOXE_MOUSEHOVER													15
#define DISPID_UPDWNTXTBOXE_MOUSELEAVE													16
#define DISPID_UPDWNTXTBOXE_MOUSEMOVE														17
#define DISPID_UPDWNTXTBOXE_MOUSEUP															18
#define DISPID_UPDWNTXTBOXE_OLEDRAGDROP													19
#define DISPID_UPDWNTXTBOXE_OLEDRAGENTER												20
#define DISPID_UPDWNTXTBOXE_OLEDRAGLEAVE												21
#define DISPID_UPDWNTXTBOXE_OLEDRAGMOUSEMOVE										22
#define DISPID_UPDWNTXTBOXE_OUTOFMEMORY													23
#define DISPID_UPDWNTXTBOXE_RCLICK															24
#define DISPID_UPDWNTXTBOXE_RDBLCLICK														25
#define DISPID_UPDWNTXTBOXE_RECREATEDCONTROLWINDOW							26
#define DISPID_UPDWNTXTBOXE_RESIZEDCONTROLWINDOW								27
#define DISPID_UPDWNTXTBOXE_TEXTCHANGED													28
#define DISPID_UPDWNTXTBOXE_TRUNCATEDTEXT												29
#define DISPID_UPDWNTXTBOXE_VALUECHANGED												DISPID_VALUE
#define DISPID_UPDWNTXTBOXE_VALUECHANGING												30
#define DISPID_UPDWNTXTBOXE_WRITINGDIRECTIONCHANGED							31
#define DISPID_UPDWNTXTBOXE_MOUSEWHEEL													32
#define DISPID_UPDWNTXTBOXE_XCLICK															33
#define DISPID_UPDWNTXTBOXE_XDBLCLICK														34


// IUpDownAccelerator
// properties
#define DISPID_UDA_ACTIVATIONTIME																1
#define DISPID_UDA_INDEX																				2
#define DISPID_UDA_STEPSIZE																			DISPID_VALUE
// methods


// IUpDownAccelerators
// properties
#define DISPID_UDAS_ITEM																				DISPID_VALUE
#define DISPID_UDAS__NEWENUM																		DISPID_NEWENUM
// methods
#define DISPID_UDAS_ADD																					1
#define DISPID_UDAS_COUNT																				2
#define DISPID_UDAS_REMOVE																			3
#define DISPID_UDAS_REMOVEALL																		4


// IVirtualUpDownAccelerator
// properties
#define DISPID_VUDA_ACTIVATIONTIME															1
#define DISPID_VUDA_INDEX																				2
#define DISPID_VUDA_STEPSIZE																		DISPID_VALUE
// methods


// IVirtualUpDownAccelerators
// properties
#define DISPID_VUDAS_ITEM																				DISPID_VALUE
#define DISPID_VUDAS__NEWENUM																		DISPID_NEWENUM
// methods
#define DISPID_VUDAS_COUNT																			1


// IOLEDataObject
// properties
// methods
#define DISPID_ODO_CLEAR																				1
#define DISPID_ODO_GETCANONICALFORMAT														2
#define DISPID_ODO_GETDATA																			3
#define DISPID_ODO_GETFORMAT																		4
#define DISPID_ODO_SETDATA																			5
#define DISPID_ODO_GETDROPDESCRIPTION														6
#define DISPID_ODO_SETDROPDESCRIPTION														7
